### ISSUE TITLE
Why the examples explore.rs can't  not causing CPU spikes?

### ISSUE THREAD

**Issue by thouger** [mattsse/voyager#4]
I test at two pc in windows,total average CPU usage about 60%.Using async code can't causing CPU spikes.I find some similar answer [https://users.rust-lang.org/t/why-is-this-async-code-not-causing-cpu-spikes/34827](url).is that because `collector.next().await`?
And they gave the answer that is to use `thread::spawn`.
I want to know if it's the same reason here, or something else.Can causing CPU spikes by only use async ?

**Comment by mattsse** [comment]
I'm not sure I understood you completely.
Are you encountering high CPU spikes or is your CPU not utilized?
Maybe you could share a minimal, reproducible example of your program?

**Comment by thouger** [comment]
The code is [https://github.com/mattsse/voyager/blob/main/examples/explore.rs](url),why does it not cause CPU (core) to be blocked at 100%?
Is there any block?

**Comment by mattsse** [comment]
This examples makes quite a lot requests which are executed asynchronously, so if your CPU is not maxed out, this most likely means that responses are pending. and there isn't much to do until then, or, depending on your runtime, how many worker threads are used. By default this should be the system's available cores, see [tokios runtime builder for example](https://docs.rs/tokio/1.3.0/tokio/runtime/struct.Builder.html)

**Comment by thouger** [comment]
Thank you for your answer!
